# Test the POST /upload route
POST http://localhost:8080/upload?type=file
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="file"; filename="weoo.json"
Content-Type: application/json

[
  {
    "name": "ZA001A",
    "scanned": true,
    "occupied": true,
    "detected_barcodes": ["DX9850004338"]
  },
  {
    "name": "ZA002A",
    "scanned": true,
    "occupied": false,
    "detected_barcodes": []
  }
]
------boundary--

###

# Test the GET /view?file=reports/report.json&action=download route
GET http://localhost:8080/view?file=reports/report_13-10-2024_22:36:28_tfwuRaKeQ2-UBWEgupSEHA.json&action=download
Accept: application/json

###

# Test the GET /view?file=reports/report.json route
GET http://localhost:8080/view?file=reports/report_13-10-2024_22:36:28_tfwuRaKeQ2-UBWEgupSEHA.json
Accept: application/json

###

# Test the POST /report route
POST http://localhost:8080/report
Content-Type: application/json

{"files": ["mini-cust.csv","mini-robot.json" ]}

###

