# Test the GET /view/{id} route
GET http://localhost:8080/view/123
Accept: application/json

###

# Test the POST /upload route
POST http://localhost:8080/upload?type=json
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="file"; filename="weoo.json"
Content-Type: application/json

[
  {
    "name": "ZA001A",
    "scanned": true,
    "occupied": true,
    "detected_barcodes": ["DX9850004338"]
  },
  {
    "name": "ZA002A",
    "scanned": true,
    "occupied": false,
    "detected_barcodes": []
  }
]
------boundary--

###

# Test the GET /report route
GET http://localhost:8080/view?file=mini-report.json
Accept: application/json

###

# Test the POST /report route
POST http://localhost:8080/report
Content-Type: application/json

{"files": ["mini-cust.csv","mini-robot.json" ]}

###

# Test the POST /export route
POST http://localhost:8080/export
Content-Type: application/json

{
  "exportFormat": "csv",
  "filter": "last_month"
}
